django_project/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

django_project/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/',
         auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

django_project/django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/item/urls.py
from django.urls import path
from .views import CreateStripeCheckoutSession, SuccessView, StripeWebhookView
from . import views

app_name = 'item'

urlpatterns = [
  path('', views.items, name='items'),
  path('new/', views.new, name='new'),
  path('<int:pk>/', views.detail, name='detail'),
  path('<int:pk>/edit/', views.edit, name='edit'),
  path('<int:pk>/delete/', views.delete, name='delete'),
  path("create-checkout-session/<int:pk>/", CreateStripeCheckoutSession.as_view(), name="create-checkout-session"),
  path("success/", SuccessView.as_view(), name="success"),
  path("webhooks/stripe/",StripeWebhookView.as_view(), name="stripe-webhook"),
]

django_project/item/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
  name = models.CharField(max_length=255)

  class Meta():
    ordering = ('name', )
    verbose_name_plural = 'Categories'
  
  def __str__(self):
    return self.name

class Item(models.Model):
  category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
  name = models.CharField(max_length=255)
  image = models.ImageField(upload_to="Item_Images", blank=True, null=True)
  description = models.TextField(blank=True, null=True)
  price = models.FloatField()
  sold = models.BooleanField(default=False)
  creator = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
  creationTime = models.DateTimeField(auto_now_add=True)

  class Meta():
    ordering = ('-creationTime',)

  def __str__(self):
    return self.name

django_project/item/forms.py
from django import forms
from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border bg-gray-175'

class NewItemForm(forms.ModelForm):
  class Meta:
    model = Item
    fields = ('category', 'name', 'description', 'price', 'image')
    widgets = {
      'category': forms.Select(attrs={
        'class': INPUT_CLASSES
      }),
      'name': forms.TextInput(attrs={
        'class': INPUT_CLASSES
      }),
      'description': forms.Textarea(attrs={
        'class': INPUT_CLASSES
      }),
      'price': forms.TextInput(attrs={
        'class': INPUT_CLASSES
      }),
      'image': forms.FileInput(attrs={
        'class': INPUT_CLASSES
      })
    }

class EditItemForm(forms.ModelForm):
  class Meta:
    model = Item
    fields = ('name', 'description', 'price', 'image', 'sold')
    widgets = {
      'name': forms.TextInput(attrs={
        'class': INPUT_CLASSES
      }),
      'description': forms.Textarea(attrs={
        'class': INPUT_CLASSES
      }),
      'price': forms.TextInput(attrs={
        'class': INPUT_CLASSES
      }),
      'image': forms.FileInput(attrs={
        'class': INPUT_CLASSES
      })
    }

django_project/item/views.py
import stripe
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Item
from django.contrib.auth.decorators import login_required
from .forms import NewItemForm, EditItemForm
from django.db.models import Q
from django.conf import settings
from django.views import View
from django.views.generic import TemplateView
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import  csrf_exempt

# stripe checkout page creation
stripe.api_key = settings.STRIPE_SECRET_KEY
class CreateStripeCheckoutSession(View):
    def post(self, request, *args, **kwargs):
        item = Item.objects.get(id=self.kwargs["pk"])

        checkout_session = stripe.checkout.Session.create(
            payment_method_types=["card"],
            line_items=[
                {
                    "price_data": {
                        "currency": "usd",
                        "unit_amount_decimal": float(item.price) * 100,
                        "product_data": {
                            "name": item.name,
                            "description": item.description,
                        },
                    },
                    "quantity": 1,
                }
            ],
            mode="payment",
            success_url = 'http://127.0.0.1:8000/items/success/',
            cancel_url = 'http://127.0.0.1:8000',
        )
        return redirect(checkout_session.url)

# viewing success page after transaction
class SuccessView(TemplateView):
    template_name = "item/success.html"

@method_decorator(csrf_exempt, name="dispatch")
class StripeWebhookView(View):
    """
    Stripe webhook view to handle completed checkout session event
    """
    def post(self, request, format=None):
        payload = request.body
        endpoint_secret = settings.STRIPE_WEBHOOK_SECRET
        sig_header = request.META["HTTP_STRIPE_SIGNATURE"]
        event = None

        try:
            event = stripe.Webhook.construct_event(payload, sig_header, endpoint_secret)
        except ValueError as e:
            # Invalid payload
            return HttpResponse(status=400)
        except stripe.error.SignatureVerificationError as e:
            # Invalid signature
            return HttpResponse(status=400)

        if event["type"] == "checkout.session.completed":
            print("Payment successful")

        return HttpResponse(status=200)



def items(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(sold=False)

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(
            Q(name__icontains=query) | Q(description__icontains=query))

    return render(
        request, 'item/items.html', {
            'items': items,
            'query': query,
            'categories': categories,
            'category_id': int(category_id)
        })


def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category,
                                        sold=False).exclude(pk=pk)[0:3]

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })


@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.creator = request.user
            item.save()
            url = "/items/" + str(item.id)
            return redirect(url)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New Item',
    })


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, creator=request.user)
    item.delete()

    return redirect('dashboard:index')


@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, creator=request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit item',
    })

django_project/item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block script %} 
<script src="https://js.stripe.com/v3/"></script>
{% endblock script %}

<style>
  .button-container {
      display: flex;
      justify-content: space-between;
  }
</style>

{% block content %}
<div class="grid grid-cols-5 gap-6">
  <div class="col-span-3 p-6 bg-gray-100 rounded-xl" style="display: flex; align-items: center; justify-content: center;">
    <center><img src="{{ item.image.url }}" class="rounded-xl" style="display: inline-block;"></center>
  </div>

  <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
    <p class="text-gray-600"><strong>Price: </strong>${{ item.price|floatformat:2 }}</p>
    <p class="text-gray-600"><strong>Seller: </strong>{{ item.creator.username }}</p>

    {% if item.description %}
      <p class="text-gray-600">
        <strong class="text-gray-600">Description: </strong><br>
        {{ item.description }}
      </p>
    {% endif %}

    {% if request.user == item.creator %}
      <div class="mt-6 p-6 bg-white rounded-xl">
        <p>This is your item listing!</p>
        <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Edit</a>
        <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700">Delete</a>
      </div>
    {% endif %}

    {% if request.user != item.creator %}
    <br>
    <div class="button-container">
      <a href="{% url 'conversation:new' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-blue-600 text-white rounded-xl hover:bg-blue-700" style="margin-right: 10px;">Contact Seller</a>
      {% if request.user.is_authenticated %} 
        <form action="{% url 'item:create-checkout-session' item.id %}" method="POST" class="inline-block">
          {% csrf_token %}
          <button type="submit" class="inline-block py-3 px-6 text-lg font-semibold bg-green-500 hover:bg-green-600 rounded-xl text-white">Purchase</button>
        </form>
      {% endif %}
    </div>
    {% endif %}
  </div>
</div>

<div class="mt-6 px-6 py-12 bg-neutral-100 rounded-xl">
  <h2 class="mb-12 text-2xl text-center"><b>Related Items</b></h2>
  <div class="grid grid-cols-3 gap-5">
    {% for related_item in related_items %}
      <div class="image-container">
        <a href="{% url 'item:detail' related_item.id %}">
          <div class="item-card">
            <div class="image-wrapper">
              <img src="{{ related_item.image.url }}" class="rounded-t-xl">
            </div>

            <div class="p-6 bg-white rounded-b-xl hover:bg-sky-100">
              <h2 class="text-2xl">{{ related_item.name }}</h2>
              <p class="text-gray-500">${{ related_item.price|floatformat:2 }}</p>
            </div>
          </div>
        </a>
      </div>
    {% endfor %}
  </div>
</div>

<script>
  // Get all the image containers
  const imageContainers = document.querySelectorAll('.image-container');

  // Loop through each image container
  imageContainers.forEach(container => {
    // Get the corresponding image element
    const image = container.querySelector('img');

    // Get the width of the image
    const imageWidth = image.offsetWidth;

    // Set the width of the parent div containing the name and price
    const itemDiv = container.querySelector('.p-6');
    itemDiv.style.width = `${imageWidth}px`;

    // Center the content within the item card (both horizontally and vertically)
    const itemCard = container.querySelector('.item-card');
    itemCard.style.display = 'flex';
    itemCard.style.flexDirection = 'column';
    itemCard.style.justifyContent = 'center';
    itemCard.style.alignItems = 'center';
  });
</script>

{% endblock %}

django_project/item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

<h1 class="mb-6 text-3xl"><b>{{ title }}</b></h1>

<form method="post" action="." enctype="multipart/form-data">
  {% csrf_token %}

  <div class="space-y-4" bg-gray-400>
    {{ form.as_p }}
  </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
          {% for field in form %}
            {{field.errors}}
          {% endfor %}
          {{form.non_field_errors}}
        </div>
      {% endif %}

  
  <button class="mt-6 py-4 px-8 text-lg bg-orange-400 hover:bg-orange-600 rounded-xl text-white"><b>Submit</b></button>
</form>

{% endblock %}

django_project/item/templates/item/items.html
{% extends 'core/base.html' %}

{% block title %}Browse{% endblock %}

{% block content %}
<style>
  .list-items .grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    justify-items: center;
  }
</style>

  <div class="pb-6 px-6 py-3 grid grid-cols-4 gap-4 bg-neutral-100 rounded-xl">
    <div class="col-span-1">
      <form method="get" action="{% url 'item:items' %}">
        <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Find a bike, a chair, or a car...">
        
        <button class="mt-2 py-3 px-6 text-lg bg-blue-500 text-white rounded-xl">Search</button>
      </form>

      <hr class="my-6">
      <p class="font-bold">Categories</p>

      <ul>
        {% for category in categories %}
          <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200 {% endif %}">
            <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
          </li>
        {% endfor %}
      </ul>

      <hr class="my-6">

      <ul>
        <li><a href="{% url 'item:items' %}" class="mt-2 py-3 px-6 inline-block bg-orange-400 text-lg rounded-xl text-white">Clear Filters</a></li>
      </ul>

      
    </div>

    <div class="col-span-3 list-items">
      <div class="grid grid-cols-3 gap-5 items-center">
        {% for item in items %}
          <div class="image-container">
            <a href="{% url 'item:detail' item.id %}">
              <div class="item-card">
                <div class="image-wrapper">
                  <img src="{{ item.image.url }}" class="rounded-t-xl">
                </div>
    
                <div class="p-6 bg-white rounded-b-xl hover:bg-sky-100">
                  <h2 class="text-2xl">{{ item.name }}</h2>
                  <p class="text-gray-500">${{ item.price|floatformat:2 }}</p>
                </div>
              </div>
            </a>
          </div>
        {% endfor %}
      </div>
  </div>

  <script>
    // Get all the item cards within the "Latest Postings" section
    const itemCards = document.querySelectorAll('.list-items .item-card');
  
    let totalWidth = 0;
    let numCards = 0;
  
    // Loop through each item card to calculate the total width
    itemCards.forEach(card => {
      const image = card.querySelector('img');
      totalWidth += image.offsetWidth;
      numCards++;
    });
  
    // Calculate the average width
    const averageWidth = totalWidth / numCards;
  
    // Set the average width for each item card and scale the image width accordingly
    itemCards.forEach(card => {
      card.style.width = `${averageWidth}px`;
  
      const image = card.querySelector('img');
      const imageWidth = image.offsetWidth;
      const scaleFactor = averageWidth / imageWidth;
      image.style.width = `${imageWidth * scaleFactor}px`;
    });
  </script>
{% endblock %}

django_project/item/templates/item/success.html
{% extends "core/base.html" %}
{% block title %} Payment Success {% endblock title%}


{% block content %}
<style>
.centered-container {
    position: absolute;
    top: 45%;
    left: 50%;
    transform: translate(-50%, -50%);
    text-align: center;
}
</style>

<div class="centered-container">
    <div>
        <h1 style="font-size: 25px;">Your payment has been confirmed. </h1> 
        <p> Be sure to contact the seller for updates on shipping </p>
        <a href="{% url 'core:index' %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-blue-600 text-white rounded-xl hover:bg-blue-700">Return to Marketplais</a>
    </div>
</div>
{% endblock content %}