django_project/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

django_project/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/',
         auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

django_project/dashboard/urls.py
from django.urls import path
from . import views

app_name ='dashboard'

urlpatterns = [
  path('', views.index, name='index'),
]

django_project/django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/item/urls.py
from django.urls import path
from .views import CreateStripeCheckoutSession, SuccessView, StripeWebhookView
from . import views

app_name = 'item'

urlpatterns = [
  path('', views.items, name='items'),
  path('new/', views.new, name='new'),
  path('<int:pk>/', views.detail, name='detail'),
  path('<int:pk>/edit/', views.edit, name='edit'),
  path('<int:pk>/delete/', views.delete, name='delete'),
  path("create-checkout-session/<int:pk>/", CreateStripeCheckoutSession.as_view(), name="create-checkout-session"),
  path("success/", SuccessView.as_view(), name="success"),
  path("webhooks/stripe/",StripeWebhookView.as_view(), name="stripe-webhook"),
]

django_project/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
  username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username', 'class': 'w-full py-4 px-6 rounded-xl'}))
  password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'class': 'w-full py-4 px-6 rounded-xl', 'data-toggle': 'password'}))


class SignupForm(UserCreationForm):
  class Meta():
    model = User
    fields = ('username', 'email', 'password1', 'password2')

  username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username', 'class': 'w-full py-4 px-6 rounded-xl'}))
  email = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'E-mail', 'class': 'w-full py-4 px-6 rounded-xl'}))
  password1 = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Password', 'class': 'w-full py-4 px-6 rounded-xl'}))
  password2 = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Confirm Password', 'class': 'w-full py-4 px-6 rounded-xl'}))

django_project/core/views.py
from django.shortcuts import render, redirect
from .forms import SignupForm
from item.models import Category, Item
from django.contrib.auth import logout

def index(request):
    items = Item.objects.filter(sold=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
  form = SignupForm()
  if request.method == 'POST':
    form = SignupForm(request.POST)
    if form.is_valid():
      form.save()
      return redirect('/login/')
    
  return render(request, 'core/signup.html', {'form': form})

def logout_view(request):
  logout(request)
  redirect(request)
  

django_project/core/templates/core/base.html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content = "width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="/media/favicon.ico">
    <title>{% block title %}{% endblock %} | Marketplais </title>
    
    <style>
          /* Set the minimum height of the page container */
    html, body {
      height: 100%;
      margin: 0;
      padding: 0;
    }

    /* Style for the page container */
    .page-container {
      display: flex;
      flex-direction: column;
      min-height: 100%;
    }

    /* Style for the main content section */
    .main-content {
      flex: 1;
      /* Add additional styles for your main content section */
    }

    /* Style for the footer */
    footer {
      background-color: #777;
      color: #fff;
      padding: 20px;
    }
    </style>
  </head>

  <body class="bg-neutral-300">
    <div class="page-container"> 
      <div class="main-content">
    <nav class="py-6 px-6 flex justify-between bg-neutral-100 items-center border-white">
      <a href="/" class="text-xl font-semibold"><img src="/media/marketplais_logo.png" alt="Marketplais" style="width:420px;height:75px"></a>
      <div class = "space-x-6">
        <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

      {% if request.user.is_authenticated %}  
        <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">Post New Item</a>
        <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-blue-600 text-white rounded-xl hover:bg-blue-700">Inbox</a>
        <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-blue-600 text-white rounded-xl hover:bg-blue-700">Dashboard</a>
        <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-blue-600 text-white rounded-xl hover:bg-blue-700">Sign Out</a>
      {% else %} 
        <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-blue-600 text-white rounded-xl hover:bg-blue-700">Sign Up</a>
        <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-blue-600 text-white rounded-xl hover:bg-blue-700">Log In</a>
      {% endif %}
        
      </div>
    </nav>
    
    <div class="px-6 py-6">
      {% block content %}
      {% endblock %}
    </div>
    </div>

    <footer class="py-6 px-6 flex justify-between bg-gray-700 bottom-0 left-0 w-full" style="width: fit-content;">
      <div class="w-2/3 pr-10">
        <h3 class="mb-5 font-bold text-gray-400 py-0">About</h3>
        <p class="text-base text-gray-500">Welcome to Marketplais, your one-stop-shop for all your online shopping needs. Our platform is designed to provide you with a seamless and convenient shopping experience, where you can browse a wide range of products from the comfort of your own home.

At Marketplais, we're passionate about connecting buyers with high-quality products at affordable prices. We work with a network of trusted suppliers and brands to bring you the latest and greatest products on the market. From electronics and fashion to home essentials, we've got it all.

Thank you for choosing Marketplais for your online shopping needs.</p>
      </div>

      <div class"w-1/3">
        <h3 class="mb-5 font-bold text-gray-400 py-0">Menu</h3>

        <ul class="space-y-2">
          <li><a href="#" class = "text-lg text-orange-500 hover:text-orange-700">Contact</a></li>
          <li><a href="#" class = "text-lg text-orange-500 hover:text-orange-700">Privacy Policy</a></li>
          <li><a href="#" class = "text-lg text-orange-500 hover:text-orange-700">Terms of Use</a></li>
        </ul>

      </div>
    </footer>
    </div>
  </body>
</html>

django_project/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
  Welcome
{% endblock %}


{% block content %}
<style>
  .list-items .grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    justify-items: center;
  }
</style>

<div class="mt-6 px-6 py-12 bg-neutral-100 rounded-xl list-items">
  <h2 class="mb-12 text-2xl text-center"><b>Latest Postings</b></h2>  
  <div class="grid grid-cols-3 gap-5 items-center">
    {% for item in items %}
      <div class="image-container">
        <a href="{% url 'item:detail' item.id %}">
          <div class="item-card">
            <div class="image-wrapper">
              <img src="{{ item.image.url }}" class="rounded-t-xl">
            </div>

            <div class="p-6 bg-white rounded-b-xl hover:bg-sky-100">
              <h2 class="text-2xl">{{ item.name }}</h2>
              <p class="text-gray-500">${{ item.price|floatformat:2 }}</p>
            </div>
          </div>
        </a>
      </div>
    {% endfor %}
  </div>
</div>

<div class="mt-6 px-6 py-12 bg-neutral-100 rounded-xl">
  <h2 class="mb-12 text-2xl text-center"><b>Categories</b></h2>

  <div class="grid grid-cols-3 gap-5">
    {% for category in categories %}
      <div>
        <a href="#">
          <div class="p-6 bg-white rounded-xl hover:bg-orange-100">
            <h2 class="text-2xl">{{ category.name }}</h2>
            {%  if category.items.count == 1 %}
              <p class="text-gray-500">{{ category.items.count }} Item</p>
            {%  else %}
            <p class="text-gray-500">{{ category.items.count }} Items</p>
            {%  endif %}
          </div>
        </a>
      </div>
    {% endfor %}
  </div>
</div>

<script>
  // Get all the item cards within the "Latest Postings" section
  const itemCards = document.querySelectorAll('.list-items .item-card');

  let totalWidth = 0;
  let numCards = 0;

  // Loop through each item card to calculate the total width
  itemCards.forEach(card => {
    const image = card.querySelector('img');
    totalWidth += image.offsetWidth;
    numCards++;
  });

  // Calculate the average width
  const averageWidth = totalWidth / numCards;

  // Set the average width for each item card and scale the image width accordingly
  itemCards.forEach(card => {
    card.style.width = `${averageWidth}px`;

    const image = card.querySelector('img');
    const imageWidth = image.offsetWidth;
    const scaleFactor = averageWidth / imageWidth;
    image.style.width = `${imageWidth * scaleFactor}px`;
  });
</script>
{% endblock %}

django_project/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}
  Login
{% endblock %}

{% block content %}
<div style="display: flex; justify-content: center; align-items: center; height: 55vh">
  <div class="w-1/2 my-6 mx-auto bg-neutral-100 px-6 py-3 rounded-xl">
    <h1 class="mb-6 text-3xl">Login</h1>
    <form method="post" action=".">
      {% csrf_token %}

      <div class="mb-3">
        <label class="inline-block mb-2">
          Username
        </label><br>
        {{form.username}}
      </div>

      <div class="mb-3">
        <label class="inline-block mb-2">
          Password 
        </label><br>
        {{form.password}}
      </div>

      {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
          {% for field in form %}
            {{field.errors}}
          {% endfor %}
          {{form.non_field_errors}}
        </div>
      {% endif %}
      <button class="py-4 px-8 text-lg bg-orange-400 hover:bg-orange-600 rounded-xl text-white"><b>Submit</b></button>
    </form>
  </div>
</div>
{% endblock %}

django_project/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}
  Sign Up
{% endblock %}

{% block content %}
  <div class="w-1/2 px-6 py-3 my-6 mx-auto bg-neutral-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign Up</h1>
    <form method="post" action=".">
      {% csrf_token %}

      <div class="mb-3">
        <label class="inline-block mb-2">
          Username
        </label><br>
        {{form.username}}
      </div>

      <div class="mb-3">
        <label class="inline-block mb-2">
          Email
        </label><br>
        {{form.email}}
      </div>

      <div class="mb-3">
        <label class="inline-block mb-2">
          Password 
        </label><br>
        {{form.password1}}
      </div>

      <div class="mb-3">
        <label class="inline-block mb-2">
          Re-enter Password
        </label><br>
        {{form.password2}}
      </div>

      {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
          {% for field in form %}
            {{field.errors}}
          {% endfor %}
          {{form.non_field_errors}}
        </div>
      {% endif %}
      <button class="py-4 px-8 text-lg bg-orange-400 hover:bg-orange-600 rounded-xl text-white"><b>Submit</b></button>
    </form>
  </div>
{% endblock %}